//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnsDatTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BnsDatTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Translate 的本地化字符串。
        /// </summary>
        internal static string AutoTranslateTabText {
            get {
                return ResourceManager.GetString("AutoTranslateTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Original 的本地化字符串。
        /// </summary>
        internal static string BackupOriginalCheckBoxText {
            get {
                return ResourceManager.GetString("BackupOriginalCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .bin File: 的本地化字符串。
        /// </summary>
        internal static string BinFileLabelText {
            get {
                return ResourceManager.GetString("BinFileLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bin Files 的本地化字符串。
        /// </summary>
        internal static string BinFilesTabText {
            get {
                return ResourceManager.GetString("BinFilesTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 64-bit 的本地化字符串。
        /// </summary>
        internal static string Bit64CheckBoxText {
            get {
                return ResourceManager.GetString("Bit64CheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .dat File: 的本地化字符串。
        /// </summary>
        internal static string DatFileLabelText {
            get {
                return ResourceManager.GetString("DatFileLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dat Files 的本地化字符串。
        /// </summary>
        internal static string DatFilesTabText {
            get {
                return ResourceManager.GetString("DatFilesTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decode 的本地化字符串。
        /// </summary>
        internal static string DecodeButtonText {
            get {
                return ResourceManager.GetString("DecodeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dump 的本地化字符串。
        /// </summary>
        internal static string DumpButtonText {
            get {
                return ResourceManager.GetString("DumpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encode 的本地化字符串。
        /// </summary>
        internal static string EncodeButtonText {
            get {
                return ResourceManager.GetString("EncodeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encode/Decode 的本地化字符串。
        /// </summary>
        internal static string EncodeDecodeTabText {
            get {
                return ResourceManager.GetString("EncodeDecodeTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string ExportButtonText {
            get {
                return ResourceManager.GetString("ExportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Folder location 的本地化字符串。
        /// </summary>
        internal static string GetFolderLocationCheckBoxText {
            get {
                return ResourceManager.GetString("GetFolderLocationCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key: 的本地化字符串。
        /// </summary>
        internal static string KeyLabelText {
            get {
                return ResourceManager.GetString("KeyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string LanguageTabText {
            get {
                return ResourceManager.GetString("LanguageTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 local.dat: 的本地化字符串。
        /// </summary>
        internal static string LocalDatLabelText {
            get {
                return ResourceManager.GetString("LocalDatLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log: 的本地化字符串。
        /// </summary>
        internal static string LogGroupBoxText {
            get {
                return ResourceManager.GetString("LogGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual Translate 的本地化字符串。
        /// </summary>
        internal static string ManualTranslateTabText {
            get {
                return ResourceManager.GetString("ManualTranslateTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge 的本地化字符串。
        /// </summary>
        internal static string MergeButtonText {
            get {
                return ResourceManager.GetString("MergeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode: 的本地化字符串。
        /// </summary>
        internal static string ModeLabelText {
            get {
                return ResourceManager.GetString("ModeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Folder: 的本地化字符串。
        /// </summary>
        internal static string OutputFolderLabelText {
            get {
                return ResourceManager.GetString("OutputFolderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output: 的本地化字符串。
        /// </summary>
        internal static string OutputLabelText {
            get {
                return ResourceManager.GetString("OutputLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repack 的本地化字符串。
        /// </summary>
        internal static string RepackButtonText {
            get {
                return ResourceManager.GetString("RepackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repack Folder: 的本地化字符串。
        /// </summary>
        internal static string RepackFolderLabelText {
            get {
                return ResourceManager.GetString("RepackFolderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source File: 的本地化字符串。
        /// </summary>
        internal static string SourceFileLabelText {
            get {
                return ResourceManager.GetString("SourceFileLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source Key: 的本地化字符串。
        /// </summary>
        internal static string SourceKeyLabelText {
            get {
                return ResourceManager.GetString("SourceKeyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source: 的本地化字符串。
        /// </summary>
        internal static string SourceLabelText {
            get {
                return ResourceManager.GetString("SourceLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string StartButtonText {
            get {
                return ResourceManager.GetString("StartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target File: 的本地化字符串。
        /// </summary>
        internal static string TargetFileLabelText {
            get {
                return ResourceManager.GetString("TargetFileLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Key: 的本地化字符串。
        /// </summary>
        internal static string TargetKeyLabelText {
            get {
                return ResourceManager.GetString("TargetKeyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target: 的本地化字符串。
        /// </summary>
        internal static string TargetLabelText {
            get {
                return ResourceManager.GetString("TargetLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        internal static string ToolsGroupBoxText {
            get {
                return ResourceManager.GetString("ToolsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate 的本地化字符串。
        /// </summary>
        internal static string TranslateButtonText {
            get {
                return ResourceManager.GetString("TranslateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unpack 的本地化字符串。
        /// </summary>
        internal static string UnpackButtonText {
            get {
                return ResourceManager.GetString("UnpackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 xml.dat 的本地化字符串。
        /// </summary>
        internal static string XmlDatCheckBoxText {
            get {
                return ResourceManager.GetString("XmlDatCheckBoxText", resourceCulture);
            }
        }
    }
}
